### ISSUE TITLE
Update dialog not closed when "UPDATE" is pressed

### ISSUE THREAD

**Issue by jusuf-el** [kauemurakami/app_version_update#18]
When I press "UPDATE" from the update dialog, the app is opened in the Play Store app (which is fine and works as expected), but when I return to the app (without updating the app), the dialog is still open. Then I need to press on "UPDATE LATER" or somewhere outside the app in order to close the dialog.

I don't see any possibility to add a callback for closing the dialog...

Is there any possibility of doing this?

**Comment by jusuf-el** [comment]
The workaround is to use a custom dialog and "re-use" the code from the package for opening the storeUrl, and then adding the statement for closing the dialog.

But, still it would be fine and very time-consuming if you add a callback parameter for the actions. Thank you!

**Comment by kauemurakami** [comment]
https://github.com/kauemurakami/app_version_update/issues/20

See this comment, I really need an update to the package to provide some feedback, I will do it soon.
