### ISSUE TITLE
Callback on any of the buttons is pressed

### ISSUE THREAD

**Issue by spiderion** [kauemurakami/app_version_update#20]
I would like to have a callback when an update is tapped so I can record the analytics on what the user has done.

**Comment by kauemurakami** [comment]
You can use a mandatory update, if it doesn't update you will be unable to use the app or close this widget.

And about the return, perhaps you can use package_info_plus compared to the api, for example here in github actions I always give a get in my version, even as a reference to how many people updated and so on.

I will also check the case, if I can add anything about it.
