### ISSUE TITLE
not working in macOS

### ISSUE THREAD

**Issue by Dr-AhmadTaha** [kauemurakami/app_version_update#21]
when running on macOS, it didn't work,  I got this error

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unkown platform
#0      fetchVersion (package:app_version_update/core/functions/fetch_version.dart:26:5)
<asynchronous suspension>
#1      AppVersionUpdate.checkForUpdates (package:app_version_update/app_version_update.dart:32:27)
<asynchronous suspension>
#2      _MyHomePageState.checkIosMacosUpdate (package:egydosecalcfree/main.dart:6282:7)
<asynchronous suspension>

**Comment by kauemurakami** [comment]
I haven't added support for Mac yet :/ I'll try to do so as soon as possible
