### ISSUE TITLE
Android can close the mandatory update by tapping the native back button

### ISSUE THREAD

**Issue by spiderion** [kauemurakami/app_version_update#22]
A mandatory update should not allow the user to skip. On android users are able to tap on the back button and the update popup disappears.

**Comment by kauemurakami** [comment]
If it is a mandatory update it will not let you close it until it is updated

**Comment by kauemurakami** [comment]
I working on it, start implementation stay in `5.0.1`, i will create an observable variable when returning from the store to the app, remaking the call to see if the version is the same to close automatically.

**Comment by kauemurakami** [comment]
Use PopScope widget on your page to prevent the back effect when using the hardware button or gestures when on an infinite screen
