### ISSUE TITLE
alway show old version ,when my app have new version in store?

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [kauemurakami/app_version_update#24]
my new app version is 1.11.27 , your lib show 1.11.26 ?? why..?

**Comment by nguyenleanhkhoa** [comment]
![Screenshot 2024-03-14 at 11 40 42](https://github.com/kauemurakami/app_version_update/assets/13627112/6d323ef2-7776-491d-a22d-492697f85918)
![Screenshot 2024-03-14 at 11 41 00](https://github.com/kauemurakami/app_version_update/assets/13627112/ffed5b6c-0076-4bb8-bb91-7352ffb1a56f)

**Comment by kauemurakami** [comment]
Ok, but show me your `version: x.x.x` in your `pubspec.yaml` please.

**Comment by kauemurakami** [comment]
I release new version 5.0.0, you can test and return here pls?
