### ISSUE TITLE
Apps in public beta -> Aplication not found in Play Store, verify your app id. 

### ISSUE THREAD

**Issue by GeeksEmpireOfficial** [kauemurakami/app_version_update#25]
I tried to use it for apps in public beta and got this Exception; Aplication not found in Play Store, verify your app id.

**Comment by kauemurakami** [comment]
Apps in beta version also have ids, look for your app in the store or stores and check the code/id in the url example `https://play.google.com/store/apps/details?id=com.instagram.lite` .
If the app is like Instagram, which provides a beta version testing program, the user must choose after entering the normal app, would this be the case?

**Comment by kauemurakami** [comment]
@GeeksEmpireOfficial Test with new version `5.0.1` pls
