### ISSUE TITLE
The app distributed in a specific region requires a country code. This part is missing in your code.

### ISSUE THREAD

**Issue by vyekahs** [kauemurakami/app_version_update#34]
I am using the code you provided well. Thank you very much. However, there is an error in version 5.0.1. For apps distributed in specific countries, a country code needs to be entered, but your code is missing the part where the country code should be entered.
I am leaving the code here because I do not know how to work together.

data = await fetchIOS(packageInfo: packageInfo, appleId: appleId);

missing here

**Comment by kauemurakami** [comment]
Fixed in https://github.com/kauemurakami/app_version_update/pull/36
