### ISSUE TITLE
Aplication not found in Play Store, verify your app id. version mismatch for ios 

### ISSUE THREAD

**Issue by JiyadAhammad** [kauemurakami/app_version_update#35]
Aplication not found in Play Store, verify your app id.

app already in playstore with same app id 

getting exception in android

**Comment by ivan-topp-espol** [comment]
First of all, thank you very much for the package.

I have the same error with version 5.0.1, but with version 4.0.2 it works fine. I would like to use version 5.0.1 because it has version package_info_plus ^8.0.0. I suspect it is due to something with the country, in version ^5.0.0 you can't specify the country anymore.

Thank you very much in advance, I hope this can be fixed soon.

**Comment by Hmmza-tariq** [comment]
Hey, I was also facing the same issue but solved it by replacing the version from:
` app_version_update: ^5.0.1
`
to:
`app_version_update: 4.0.0
`
My app was live but in specific country so maybe newer version of the package was unable to detect it.

**Comment by JiyadAhammad** [comment]
i updated the pacakge to 5.0.1 there its working fine for android and getting proper response 
but in ios im getting issue in response 
my application is running in ios 1.0.10 version 
but the response from the app is getting 1.0.9
the same is working fine in android and getting response 1.0.10

https://apps.apple.com/us/app/ginni-social/id6504367924?uo=4 (1.0.10)

the above mentioned the app link 

the below is the response of the plugin with url as well as version 

[log] https://apps.apple.com/us/app/ginni-social/id6504367924?uo=4 
[log] 1.0.9

**Comment by banzaez** [comment]
For my case, I corrected it like this:

fetch_version.dart

regex = RegExp(r'"\]\]\],null,null,null,\[\[\["(.*?)"\]\]\]');
-> 
regex = RegExp(r'\]\]\],null,null,null,\[\[\["(.*?)"\]\],');

**Comment by AnyKay00** [comment]
Having the same problem with version 5.0.3 - Apple not working, Android works fine

Any solutions? Is going back to an older version okay?

**Comment by stam0912** [comment]
It worked on iOS and Android before, but I forgot which version I was using. After I upgraded app_version_update to ^5.0.3 and connectivity_plus to ^8.0.2, it doesn't work on both platform anymore.

**Comment by TheMeanCanEHdian** [comment]
Same experience here, after updating from 4 to 5 it is no longer working. My app has other upgraded packages that require connectivity_plus 8.0.2 so I have to stop using this until there is a resolution.

**Comment by stam0912** [comment]
> Same experience here, after updating from 4 to 5 it is no longer working. My app has other upgraded packages that require connectivity_plus 8.0.2, so I have to stop using this until there is a resolution.

Try specify the country, it worked for me.

**Comment by stam0912** [comment]
> ios works, android doesn't. For my case, I corrected it like this:
> 
> fetch_version.dart
> 
> regex = RegExp(r'"]]],null,null,null,[[["(._?)"]]]'); -> regex = RegExp(r']]],null,null,null,[[["(._?)"]],');

I changed it to regex = RegExp(r'"\]\]\]\],null,null,null,\[\[\["(.*?)"\]\],'); and it now works fine on Android.
I verified the regex with this [online tool](https://regex101.com).

**Comment by vijayvaghela72** [comment]
i'm getting same issue in android . ios it's working fine. version 5.0.3

if there is any update quick fix let me know.

**Comment by kauemurakami** [comment]
I released new version today, but in my tests this regex it's ok, testing now pls.

**Comment by vijayvaghela72** [comment]
@kauemurakami brother, Thank you so much for quick response.

version 6.0.0 is working fine for both android and iOS.

😀

**Comment by redDwarf03** [comment]
Hi. 
for example, this uri doesn't work with.version 6.0.0 (playstore)
`https://play.google.com/store/apps/details?id=net.archethic.archethic_wallet`

Could you reopen this issue please
