### ISSUE TITLE
Reopen | alway show old version ,when my app have new version in store

### ISSUE THREAD

**Issue by Aashish-Dahal** [kauemurakami/app_version_update#37]
My new app store version is 1.0.40, your package show 1.31 old version info ?? why..??

**Comment by kauemurakami** [comment]
Can you provide the id of your published application?
In my tests using TikTok https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically -> The id **id=com.zhiliaoapp.musically** is in version 36.3.3, access page and click in **About this app** ->
```shell
Local version x.x.x Last version found: 36.3.3
```
And in my tests, in my `pubspec.yaml` with version 1.0.0 it opens the update window, if it is equal or greater nothing happens, you can see the feedback in screenshots of the example.
Check in the store if your app is really in this version, and is not in a beta test, internal test for example, this will only work with the production link with the production app, if you use an approval one you must use its url

**Comment by kauemurakami** [comment]
If you testing, to change version, local version, make this:

1. Change example version.
2. Flutter clean
3. Flutter run

Hot reload don't update localversion, i testing this today.
Sorry for long time, I'm a little far from here.
If don't work after steps, reopen issue pls.
