### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by aucshow-wjb** [kauemurakami/app_version_update#4]
![image](https://user-images.githubusercontent.com/110958823/210287644-abedd78f-4351-406e-9771-dc807a9b8576.png)

Null check operator used on a null value

![image](https://user-images.githubusercontent.com/110958823/210287668-fb80c54c-06af-4e7b-b9e2-59cf9eeef4c8.png)

?

**Comment by kauemurakami** [comment]
hi, i go verify this.

**Comment by kauemurakami** [comment]
I have just run the tests, check your application data entered.

```
      await AppVersionUpdate.checkForUpdates(
              appleId: '1459706595',
              playStoreId: 'com.byebnk.app',
              country: 'br')
          .then((data) async {
        print(data.platform);  -> TargetPlatform.android
        print(data.storeUrl); -> https://play.google.com/store/apps/details?id=com.MYAPP.app&hl=br
        print(data.canUpdate); -> true;
        print(data.storeVersion); -> 1.0.0 ( local is 0.9.9 )
        if (data.canUpdate!) {
          await AppVersionUpdate.showAlertUpdate(
            appVersionResult: data,
            context: Get.context!,
            backgroundColor: bg_grey_color,
            title: 'Uma versão mais recente está disponível.',
            content:
                'Gostaria de atualizar seu aplicativo para a versão mais recente?',
            updateButtonText: 'ATUALIZAR',
            cancelButtonText: 'DEPOIS',
            titleTextStyle: body_white_16_700,
            contentTextStyle: body_white_14,
          );
        }
      });
```

This error must happen because you can't find the app in the store, check the ids and information and try again.

**Comment by kauemurakami** [comment]
Acabei de executar os testes, verifique os dados do seu aplicativo inseridos.

      await AppVersionUpdate.checkForUpdates(
              appleId: '12345678901,
              playStoreId: 'com.MYAPP.com',
              country: 'br')
          .then((data) async {
        print(data.platform);  -> TargetPlatform.android
        print(data.storeUrl); -> https://play.google.com/store/apps/details?id=com.MYAPP.app&hl=br
        print(data.canUpdate); -> true;
        print(data.storeVersion); -> 1.0.0 ( local is 0.9.9 )
        if (data.canUpdate!) {
          await AppVersionUpdate.showAlertUpdate(
            appVersionResult: data,
            context: Get.context!,
            backgroundColor: bg_grey_color,
            title: 'Uma versão mais recente está disponível.',
            content:
                'Gostaria de atualizar seu aplicativo para a versão mais recente?',
            updateButtonText: 'ATUALIZAR',
            cancelButtonText: 'DEPOIS',
            titleTextStyle: body_white_16_700,
            contentTextStyle: body_white_14,
          );
        }
      });
Esse erro deve acontecer porque você não encontra o app na loja, verifique os ids e informações e tente novamente.

**Comment by kauemurakami** [comment]
are you using ios or android? If you are using ios I will perform another test.

**Comment by kauemurakami** [comment]
I have just tested it on the iOS 15.2 simulator - iphone 13 Pro and everything is ok, checking with the pple store version correctly
