### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

### ISSUE THREAD

**Issue by armagangok** [kauemurakami/app_version_update#41]

**Comment by armagangok** [comment]
The full stacktrace

I/flutter (25001): │ 🐛 MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info),#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:80:26)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #4      fetchVersion (package:app_version_update/core/functions/fetch_version.dart:18:23)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #5      AppVersionUpdate.checkForUpdates (package:app_version_update/app_version_update.dart:31:18)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 #6      VersionUpdateHelper.checkForUpdate (package:pomodoro_app/core/helpers/version_update/version_update_helper.dart:13:32)
I/flutter (25001): │ 🐛 <asynchronous suspension>
I/flutter (25001): │ 🐛 
I/flutter (25001): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
W/OnBackInvokedCallback(25001): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(25001): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

**Comment by kauemurakami** [comment]
@armagangok  Try with new releases, if persist, open this issue again please.
