### ISSUE TITLE
Android: Mandatory = true, doesn't prevent user from using back button to close the bottom sheet

### ISSUE THREAD

**Issue by AnyKay00** [kauemurakami/app_version_update#44]
In Android:
When setting mandatory to true the user can still close the bottom sheet and dialogs with the back button of the phone.

That can be fixed with wrapping the BottomSheetUpdateVersion Widget in appp_version_update.dart with the Widget 
Popscope() and setting the attribute "canPop" to false - if mandatory is set to true.

**Comment by Macacoazul01** [comment]
@AnyKay00 if he approves, the problem is fixed.

**Comment by kauemurakami** [comment]
@Macacoazul01 make changes, and now, i'ts work.
https://github.com/kauemurakami/app_version_update/pull/45
